### PR TITLE
[Enhancement] Lazy loading tree

### PR DESCRIPTION
**Pull request by Thatkookooguy**
Changed directory tree behavior on BE & FE to implement lazy loading (loading each directory when it is requested).

# Work Summary
## BE
* Refactored `api.js` to two new files: `folderService.js` & `fileService.js`.
* Changed behavior of folderService get function to implement getting only the requested directory layer.
* New `folderService.js` sets the `type` attribute as the *file extension*.

## FE
* changed `directory-tree` to implement lazy loading using the new `folderService.get` function.
* Change file icon (and color) based on tree `type` attribute.
* On initialization, The initial `tmp_path` directory will be loaded (moved to a variable for convenience).

# Some known issues
* `14 - output.name = 'Development';` is hard-coded. Needs to just get the directory name and **of course it needs to check that the path is actually a directory!!!**.

[Review on Reviewable](https://reviewable.io/reviews/kibibit/kibibit-code-editor/26)

### CODE REVIEW

**Comment by Thatkookooguy** [comment]
@ortichon - This is the pull request that will solve your problem. I was able to load my `Development` folder with this (and with your current pull request I can't).

Tell me if this helped. And please kindly review it :smile: 

At **Google**, we used to mark a pull request as good with a: :lgtm: tag. you can *add one in a comment* by writing ***:<span></span>lgtm:***. *Reviewable* supports a quick emoticon retrieval functionality that's pretty cool (though it's taken from *Github* :laughing: )

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kibibit/kibibit-code-editor/26#-:-K5JT6cCtIxmQ6tN0Lxa:-1284225868)*

**Comment by ortichon** [comment]
Hi,
The lazy loading works fine and behaves as expected. I checked it on my Mac machine with my home folder.

-enhancement 
Currently folder has their own icon and all but they don't have the caret triangle until selected. so the user can't know if the folder is empty of not before selecting it.

-bug
when selecting a folder with massive content (folders or files) the list getting out of bounds, we'll have to change the container div "overflow-y" to scroll

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kibibit/kibibit-code-editor/26#-:-K5S5AlBtYnGrb9yUUdS:-1691557151)*

**Comment by Thatkookooguy** [comment]
everything on the screen don't have real styling. The code editor have the same problem (with the height). We'll fix this in a new branch and create a new bug for it so it will be considered a mission.

-enhancement  I thought about removing the triangle all together, so it didn't bother me as much. We can open a bug about it but it's gonna be pretty low priority in my opinion. It's clear that a folder is empty since it's being selected instead of expanding.

I rather have an open-folder closed-folder icon toggle if you think something clearer is needed.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kibibit/kibibit-code-editor/26#-:-K5S7_O3MIhnAroLE5ct:722940705)*

**Comment by Thatkookooguy** [comment]
I'll write some follow ups I started developing for this change:

1. Sorted files and folders.
2. 20+ file extensions support
3. default file icon for unsupported files.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kibibit/kibibit-code-editor/26#-:-K5S8TyZbd2zHLvZS0zh:1736016186)*

**Comment by ortichon** [comment]
Ok, cool. great idea about the open/close folder icons.
May I merge to master?
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kibibit/kibibit-code-editor/26#-:-K5S9VhtuMmUpp2-NKdU:-900447067)*

**Comment by Thatkookooguy** [comment]
Sure. Go ahead :wink: 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kibibit/kibibit-code-editor/26#-:-K5S9rILsKFioy_oRtVb:-657416796)*

**Comment by Thatkookooguy** [comment]
# Summary
* added angular-loading-bar to `bower`
* changed directory structure to include `components`.

> Each component will have the following folder structure:
```
[component_name] {
  [componentName].js
  [componentName]Template.html
  // [componentName]Style.scss (to be added later)
}
```

## [componentName].js

> Most of the time, this will include a `directive` + `controller` combo. Things like Modals don't need a `directive`:
```
angular.module('[appName]')
  .directive(function() {

	})
	.controller('[componentName]Ctrl' ,function() {

	})
```

**Pull request merged**
