### PR TITLE
[DO NOT SUBMIT] Added line length setter

### PR DESCRIPTION
**Pull request by Thatkookooguy**
# Change Summary

 - change short synopsis I [resolves #00]
 
 > additional info about this mission
 
 - change short synopsis II (mission without additional info)
 - change short synopsis III
 
## More info

(Free text here with additional photos, wikis, and additional needed information)

# :warning: MAKE SURE TO GO THROUGH THIS LIST :warning:
(reviewers ***shouldn't approve a PR without the next three checkboxs checked***)

Before you submit a PR, make sure you did the following things:
- [ ] did you link this PR to an issue?

>> Make sure there's an issue open about the change you did *(open one if there isn't)*. link this PR to that issue by writing `resolves #{{issue_number}}`. If this PR had several mission, link each issue in its parallel mission.

- [ ] did you lint your changes to both javascript and scss?

>> hound can be **pretty rough** at keeping our code clean and readable! make sure you format your code by running either `gulp format` or `gulp lint` and cleaning out all the ***lint errors***. If you won't, you'll have a ***long conversation*** with hound :-)

- [ ] "I'm pretty sure I'll be able to read and understand this PR, even if I wasn't the author." - ***said the PR author***

---
This change is [Reviewable](https://reviewable.io/reviews/kibibit/kibibit-code-editor/125)

### CODE REVIEW

**Comment by Thatkookooguy** [comment]
@ortichon reminding you to replace `line length` with `Ruler`

take example from Sublime Text 3:
screen shot 2016-05-10 at 00 35 28

**Comment by neilkalman-redkix** [comment]
to fix the gutter `error`, `warning` and `info` icons, add the following style to each icon:
```scss
name {
  ...
  background-size: 14px;
  background-position: 2px 2px;
}
```

@ortichon , please solve this in this PR, since now it's only a copy paste fix :wink:

**Comment by neilkalman-redkix** [comment]
very cool so far! loved the line wrap column and all the bling

**Comment by neilkalman-redkix** [comment]
some icons for the new menu items:

* line wrap: https://design.google.com/icons/#ic_wrap_text
* line wrap column: https://design.google.com/icons/#ic_tune
* ruler: https://design.google.com/icons/#ic_blur_linear

>> not sure about this one. if you find something better tell me about it :-)

* show gutter: https://design.google.com/icons/#ic_format_list_numbered
* text size: https://design.google.com/icons/#ic_format_size

>> even though I think the right way to do this is in the later added settings modal, go ahead and add this icon as well for now if it solves your problem :-)

**Comment by Thatkookooguy** [comment]
oh... and ofc you can use `em` units in the gutter fix to make the font size relative to the parent's fpnt

**Comment by ortichon** [comment]
@Thatkookooguy 
when we have a checkbox (like the line-wrap), where we put the icon?

**Comment by neilkalman-redkix** [comment]
you didn't use a checkbox. So I'm not sure if I understand the question.

The only thing you did was adding a checkbox icon when something is used.

If you meant if you should replace the checkbox, then my answer is:

1. for line-wrapping, keep the checkbox
2. for line wrapping column, change it to https://design.google.com/icons/#ic_wrap_text

also, I think these will be better for naming in the menu bar:

1. `line wrapping` === `line wrapping`
2. `line wrapping column` === `wrap after...`

The `wrap after...` button should be disabled if `line wrapping` is disabled

**Comment by ortichon** [comment]
line wrapping column -> I kind of used the same terminology I saw in sublime. I can change it if you wish.
when I said "checkbox" I kind of meant that the "line wrap" functions as checkbox, -> there is a "check" icon when it's active, so should we put the "line wrap" icon only when it's not "checked"?

I've just added "insert spaces instead of tabs"
but please see the following Ace [issue](https://github.com/ajaxorg/ace/issues/1721) - and let me know what you think we should do.
(when I copy the indented code to sublime, the arrows and backspace works well)

**Comment by neilkalman-redkix** [comment]
I know you went with the sublime terminology. But I don't think it's very intuitive. Sublime is pretty bad in the ammount of things they put in the menu bar.
Some advanced settings will be enabled\disabled from the settings modal we'll have later. So you don't have to create a menu item for each setting atm.

Take a look at other code editors besides sublime. Phycharm, Atom, Brackets, etc.

about the icons: well.. then use what I said in my last comment. I think it's a good UX.

not sure what you meant with the ace bug. once the demo will be up I'll look at it again

**Comment by neilkalman-redkix** [comment]
well.... looked at the demo and I see that the "use spaces" doesn't work. did you implement that yet?

tabs seems to work fine.

not sure if I understood the soft tabs feature thingy. Can you explain like I'm 5 please? :-P

**Comment by neilkalman-redkix** [comment]
btw... don't forget this is not an actual code review yet :-P

**Comment by neilkalman-redkix** [comment]
```scss
background-position: 0.3em 0.1em;
background-size: 1.2em;
```

you can also set this to `1em` as `background-size`. check which one looks better. Same thing with `background-position: 0.1em 0.1em;`

**Comment by ortichon** [comment]
I'm gonna remove the "wrap line column" from the menu bar.
so now we freed this icon: https://design.google.com/icons/#ic_tune 
may we use it for the ruler instead of https://design.google.com/icons/#ic_blur_linear 
?

**Comment by Thatkookooguy** [comment]
I think the icon you suggested looks like a settings icon. So I thought it's good for "additional tweaking". I'm not sure if it's a good icon for ruler. You can check if one of the other icon fonts we use have some actual ruler icon

But between the two, I prefer the original one

But I'm sure there's a good ruler icon in one of the fonts we use

**Comment by Thatkookooguy** [comment]
not sure if this is the best solution, but hey, it works :smile: 


put both `md-input-container` in this:
```html
<span class="right-side">
...
</span
```


then, apply the following style:
```scss
.status-bar {
  position: relative;
  overflow: hidden;

  .right-side {
    position: absolute;
    right: 0;
    bottom: 0;


    md-input-container {
      margin: 0;
    }
  }
}
```

**Comment by Thatkookooguy** [comment]
maybe we need a better name than `right-side`. maybe `quick-access`?

if you have a better name, go for it :-)

**Comment by Thatkookooguy** [comment]
Also, add this inside the `status-bar` class:

```scss
.status-bar {
  ...
  md-select:not([disabled]):focus .md-select-value {
    border-bottom-color: $primary;
    color: $primary;
  }
}

**Comment by neilkalman-redkix** [comment]
commenting just to check the new telegram github integration

**Pull request closed without merging**
