### PR TITLE
Add mixin

### LINKED ISSUE #227: Replace underscore with lodash + add my custom mixins
###### FEATURE
---
I have some mixin I created for both `lodash` and `chance.js`. Need to include them in `kibibit`

### PR DESCRIPTION
**Pull request by Thatkookooguy**
# Change Summary

 - Add `LODASH` instead of `underscore` [resolves #227]
 - add my special mixin into the mix :-)
 
 > Most functions in lodash's mixin are there as syntactic sugar. in `chance.js`, it just generates specific objects. this is nice for mocking small things while developing.

# :warning: MAKE SURE TO GO THROUGH THIS LIST :warning:
(reviewers ***shouldn't approve a PR without the next three checkboxs checked***)

Before you submit a PR, make sure you did the following things:
- [x] did you link this PR to an issue?

>> Make sure there's an issue open about the change you did *(open one if there isn't)*. link this PR to that issue by writing `resolves #{{issue_number}}`. If this PR had several mission, link each issue in its parallel mission.

- [x] did you lint your changes to both javascript and scss?

>> hound can be **pretty rough** at keeping our code clean and readable! make sure you format your code by running either `gulp format` or `gulp lint` and cleaning out all the ***lint errors***. If you won't, you'll have a ***long conversation*** with hound :-)

- [x] "I'm pretty sure I'll be able to read and understand this PR, even if I wasn't the author." - ***said the PR author***

### CODE REVIEW

**Comment by ortichon** [comment]
@Thatkookooguy 
why do we include `lodash` in our lib folder instead of bower-install it?

**Comment by Thatkookooguy** [comment]
@ortichon lodash ditched `bower` :-/

https://github.com/lodash/lodash/wiki/Changelog#v400

**Comment by ortichon** [comment]
@Thatkookooguy so maybe we should consider install it via `npm`? or even install all client 3rd parties via `npm`?
(it seems more and more developers ditching `bower` lately 👎 )

**Comment by Thatkookooguy** [comment]
@ortichon it's already installed using npm. I just copied it to another folder

I don't think it's necessary atm. Basically, this mostly affects our development environment since in production, gulp just merges all the files together so you don't need a lib public folder.
We can open a bug to do this later since it will probably be nice to advance to another build system.

But it's not as if there's a bug that happens because of it. And we can bypass lodash specifically pretty fast if we ever need to (by adding 2 lines to our gulpfile). That's why I think dealing with this atm is not a top priority

**Comment by ortichon** [comment]
LGTM

**Comment by Thatkookooguy** [comment]
I can change it specifically for lodash if you want

**Comment by Thatkookooguy** [comment]
We don't use LGTM anymore :-)

just use the normal github review thingy :-)

**Comment by Thatkookooguy** [comment]
It will be in another pull request

go ahead and merge this one

thanks!

**Pull request merged**
