### PR TITLE
add project avatar

### LINKED ISSUE #114: Add circular logo for projects
###### FEATURE
---
a circular avatar for the open folder\project should be present in the menu bar.
It should default to the kibibit logo (as a placeholder), be a folder icon if a folder **is selected**, but it isn't a project.
for projects: should show a logo of the project if available, or a folder icon with some mini icon on it

### PR DESCRIPTION
**Pull request by Thatkookooguy**
# Change Summary

 - Add project avatar to the menu bar [ resolves #114 ]
 
 > should work like this:
>1. placeholder of **kibibit** if no project is open
>2. project logo if a `.logo.png` file is included in the same path as `package.json` (will be supported once we parse some project details on the server)
>3. show a folder icon if a folder is selected that doesn't have a `package.json` file + `.logo.png` file to read

- [x] did you link this PR to an issue?
- [x] did you lint your changes to both javascript and scss?
- [x] "I'm pretty sure I'll be able to read and understand this PR, even if I wasn't the author." - ***said the PR author***

---
This change is [Reviewable](https://reviewable.io/reviews/kibibit/kibibit-code-editor/115)

### CODE REVIEW

**Comment by ortichon** [comment]
LGTM

**Comment by ortichon** [comment]
3 hound violations... :(
how do I unLGTM?

**Comment by Thatkookooguy** [comment]
Lol I'll fix it. I just wanted to try something so I removed some things to check if hound stopped notifying on depth of selectors

You unLGTM WITH one of the following:

```
**reject PR**
**reject this PR**
cancel LGTM
 cancel my LGTM
 :lgtm_cancel:
```

**Comment by ortichon** [comment]
cancel LGTM

**Comment by ortichon** [comment]
**reject PR**

**Comment by Thatkookooguy** [comment]
now there's no violations

tell me if you want me to fix anything else or give me a LGTM 👂

**Comment by ortichon** [comment]
Very Nice
LGTM

**Comment by ortichon** [comment]
LGTM again

**Comment by ortichon** [comment]
LGTM !

**Comment by Thatkookooguy** [comment]
thx Or :-)

**Pull request merged**
